<?php
$autosListe = [
    [
        'marke' => 'Mercedes',
        'farbe' => 'Blau',
        'ps' => 180,
        'kraftstoffart' => 'Diesel',
        'tankvolumen' => 55,
        'verbrauchProKm' => 6.2,
        'erstzulassung' => '2021-11-15',
        'preis' => 30000.00,
    ],
    [
        'marke' => 'Volkswagen',
        'farbe' => 'Schwarz',
        'ps' => 150,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 50,
        'verbrauchProKm' => 7.0,
        'erstzulassung' => '2020-08-28',
        'preis' => 22000.00,
    ],
    [
        'marke' => 'Audi',
        'farbe' => 'Silber',
        'ps' => 220,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 65,
        'verbrauchProKm' => 9.5,
        'erstzulassung' => '2022-05-10',
        'preis' => 38000.00,
    ],
    [
        'marke' => 'Ford',
        'farbe' => 'Weiß',
        'ps' => 120,
        'kraftstoffart' => 'Diesel',
        'tankvolumen' => 45,
        'verbrauchProKm' => 5.8,
        'erstzulassung' => '2019-06-02',
        'preis' => 18000.00,
    ],
    [
        'marke' => 'BMW',
        'farbe' => 'Grau',
        'ps' => 190,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 60,
        'verbrauchProKm' => 8.0,
        'erstzulassung' => '2023-02-18',
        'preis' => 35000.00,
    ],
    [
        'marke' => 'Toyota',
        'farbe' => 'Rot',
        'ps' => 140,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 55,
        'verbrauchProKm' => 6.5,
        'erstzulassung' => '2020-12-05',
        'preis' => 21000.00,
    ],
    [
        'marke' => 'Nissan',
        'farbe' => 'Blau',
        'ps' => 160,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 50,
        'verbrauchProKm' => 7.8,
        'erstzulassung' => '2021-09-20',
        'preis' => 24000.00,
    ],
    [
        'marke' => 'Volvo',
        'farbe' => 'Schwarz',
        'ps' => 200,
        'kraftstoffart' => 'Diesel',
        'tankvolumen' => 60,
        'verbrauchProKm' => 6.9,
        'erstzulassung' => '2022-03-15',
        'preis' => 32000.00,
    ],
    [
        'marke' => 'Honda',
        'farbe' => 'Gelb',
        'ps' => 130,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 45,
        'verbrauchProKm' => 5.5,
        'erstzulassung' => '2019-07-10',
        'preis' => 19000.00,
    ],
    [
        'marke' => 'Mazda',
        'farbe' => 'Grün',
        'ps' => 170,
        'kraftstoffart' => 'Benzin',
        'tankvolumen' => 55,
        'verbrauchProKm' => 7.2,
        'erstzulassung' => '2023-04-25',
        'preis' => 27000.00,
    ],
];
?>